
package soap.cibertec.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import soap.cibertec.interfaces.ObjectFactory;
import soap.cibertec.interfaces.Producto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicio", targetNamespace = "http://interfaces.cibertec.soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Servicio {


    /**
     * 
     * @param precio1
     * @param precio2
     * @return
     *     returns java.util.List<soap.cibertec.interfaces.Producto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllProducto", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListAllProducto")
    @ResponseWrapper(localName = "listAllProductoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.ListAllProductoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/listAllProductoRequest", output = "http://interfaces.cibertec.soap/servicio/listAllProductoResponse")
    public List<Producto> listAllProducto(
        @WebParam(name = "precio1", targetNamespace = "")
        double precio1,
        @WebParam(name = "precio2", targetNamespace = "")
        double precio2);

    /**
     * 
     * @param producto
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveProducto", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.SaveProducto")
    @ResponseWrapper(localName = "saveProductoResponse", targetNamespace = "http://interfaces.cibertec.soap/", className = "soap.cibertec.interfaces.SaveProductoResponse")
    @Action(input = "http://interfaces.cibertec.soap/servicio/saveProductoRequest", output = "http://interfaces.cibertec.soap/servicio/saveProductoResponse")
    public int saveProducto(
        @WebParam(name = "producto", targetNamespace = "")
        Producto producto);

}
